name: ci
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force --config-file ./mkdocs.yml
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create folder
        run: mkdir -p results && cp -R dist results
          ls results
